### PR TITLE
Review the workflow of HTML processing in comparisons #4447

### LINKED ISSUE #4353: Test failure diff shows place-holder variables
The test AdminAccountManagementPageUiTest eventually passed, but when it failed at first, the diff was like this (still contained a place holder variable):
image

### LINKED ISSUE #4447: Review the workflow of HTML processing in comparisons
The assertSameHtml() and assertSameHtmlPart() are processing both the expected and actual html documents for standardization (convertToStandardHtml) and godmode (processPageSourceForFailureCase) before running the comparison.

We need to check if it is still needed and if not, remove it.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4447 and I believe it also fixes #4353.
Refer to [this gist I made](https://gist.github.com/wkurniawan07/e1fb00be615bb34ca01f) for the rationale behind the solution.
Only one small problem though: I can't think of a better name than `GodModePartOne` and `GodModePartTwo` :p

### CODE REVIEW

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 1]
```diff
@@ -798,24 +811,19 @@ private boolean testAndRunGodMode(String filePath, String content, boolean isPar
         }
     }
     
-    public static String processPageSourceForFailureCase(String content) {
-        return processPageSourceForGodMode(content);
-    }
-    
-    
-    private static String processPageSourceForGodMode(String content) {
+    private static String processPageSourceForGodModePartOne(String content) {
```
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Since we are cleaning up Godmode, lets SLAP it. You could split this large function into smaller functional blocks and can name them more meaningfully:
(1) standardizeVariationsInInjectedValues()
(2) substituteHashedValuesWithPlaceholders()
(3) substitutePredictableButVaryingValuesWithPlaceholders()
(4) substituteUnpredictableValuesWithWildCards()

Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: The function itself could be called "processPageSourceForHtmlComparison()"

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 2]
```diff
@@ -881,6 +888,19 @@ private static String processPageSourceForGodMode(String content) {
                 // jQuery-ui CDN
                 .replace("https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js", "${lib.path}/jquery-ui.min.js");
     }
+    
+    private static String processPageSourceForGodModePartTwo(String content) {
```
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: I believe this function is only called when we are generating expected htmls. 
So we could name this one as "processPageSourceForCreatingExpectedHtml()" or smth along those lines

**Comment by thyageshm** [comment]
A very well done job on cleaning it up! Just some suggestions on naming the functions haha.
Nice catch on the redundancies.

**Comment by thyageshm** [comment]
In terms of testing this pr, try and do the following:
(1) ensure dev green (which you would have definitely done)
(2) purposely edit a html to make a browser test fail and see if the diff generated by eclipse is what we expect. (try to use feedbackResultsPage for a wide coverage of placeholders/wildcards)
(3) after (2), run with godmode and ensure the changes made in (2) are undone and no more modifications to the expected html has been made.

File: src/test/resources/pages/studentProfilePictureModalDefault.html [hunk 3]
```diff
@@ -1,45 +1,41 @@
-<div style="display: block;" class="modal fade in" id="studentPhotoUploader" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
-    <div class="modal-dialog modal-lg">
-        <div class="modal-content">
+   <div aria-hidden="false" aria-labelledby="myModalLabel" class="modal fade in" id="studentPhotoUploader" role="dialog" style="display: block;">
```
Comment (thyageshm) [inline src/test/resources/pages/studentProfilePictureModalDefault.html]: Hey btw, I am going to be regenerating this file in #4498 so, is it possible for you to reverse this change?

Comment (wkurniawan07) [inline src/test/resources/pages/studentProfilePictureModalDefault.html]: No problem at all :+1:

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 4]
```diff
@@ -881,6 +896,23 @@ private static String processPageSourceForGodMode(String content) {
                 // jQuery-ui CDN
                 .replace("https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js", "${lib.path}/jquery-ui.min.js");
     }
+    
+    private static String processPageSourceForExpectedHtmlRegeneration(String content) {
+        return replaceInjectedValuesWithPlaceholders(content);
+    }
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: This method looks redundant but in the spirit of maintainability I think it's better this way?

Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Yes I think so too. Let it be.

**Comment by thyageshm** [comment]
Hey, were you able to test the solution the way I had suggested in the prev comment?

**Comment by wkurniawan07** [comment]
Tested with the two `*CourseJoinConfirmationHTML`s, worked perfectly. You can try it yourself to make sure.

**Comment by thyageshm** [comment]
yup I will :-)

**Comment by wkurniawan07** [comment]
Added a new commit to clean up all the remaining wildcards. Also, I tried to regenerate every single HTML file used, it's all clean except for the two StudentProfilePictureModal HTMLs.

**Comment by thyageshm** [comment]
Good to go!
