### PR TITLE
StudentProfilePageUiTest test fails occasionally on line 106 #3571

### LINKED ISSUE #3571: StudentProfilePageUiTest test fails occasionally on line 106
Expecting a different status message than was shown

screen shot 2015-05-30 at 8 33 24 pm

### PR DESCRIPTION
**Pull request by MrFool**
Fixes #3571

Explanation as to why on the Issue page.

### CODE REVIEW

**Comment by damithc** [comment]
Is it better to have another `verifyStatus(expectedStatus, retryPeriod)` that retry to match the expected status for a duration? e.g. retry once per second for 10 seconds?

**Comment by MrFool** [comment]
Sounds like an even better idea, from our experiences with the other tests, sometimes it might be possible (when running the entire suite), that certain operations take > 1 second. If we retry up to 10 seconds but terminate early, we can be more sure that it will pass when it is supposed to and if it fails even after 10 seconds, there's most likely something wrong with the test (broken or what not).

I will implement that tomorrow or this weekend, gonna set back to ongoing for now. Need to focus on the JSF stuff for tomorrow morning's meeting :p

**Comment by MrFool** [comment]
Updated it to using retries

File: src/test/java/teammates/test/pageobjects/StudentProfilePage.java [hunk 1]
```diff
@@ -171,4 +176,27 @@ public void verifyPhotoSize(int height, int width) throws Exception {
                                                           .getAttribute("value"));
     }
 
+    public void verifyStatusWithRetry(String expectedStatus, int numberOfTries) {
```
Comment (damithc) [inline src/test/java/teammates/test/pageobjects/StudentProfilePage.java]: Add a comment? May be useful in other places; pull up to the parent class?

File: src/test/java/teammates/test/pageobjects/StudentProfilePage.java [hunk 2]
```diff
@@ -158,6 +159,10 @@ private void ensureGenderIsSelectedAs(String gender) {
     public void uploadPicture() {
         uploadPictureSubmit.click();
         browser.selenium.waitForPageToLoad("10000");
+        
+        // Intended compounded explicit wait due to .click()'s inconsistency in triggering selenium's
+        // waitForPageToLoad. Do not remove, can cause a higher rate of random failure in this test.
+        ThreadHelper.waitFor(1000);
```
Comment (damithc) [inline src/test/java/teammates/test/pageobjects/StudentProfilePage.java]: Do we still need this? I thought if we retry the status check, there's no need to wait here.

**Comment by MrFool** [comment]
Yeah ok, now that you mention it, it might be useful for other pages when it is possible that they also have problem with the .click() inconsistency but may currently be using explicit waits without retries or the likes, this method may be used in place of those.

I'll update it and ping again when it's done.

File: src/test/java/teammates/test/pageobjects/StudentProfilePage.java (hunk 2 above)
Comment (MrFool) [inline src/test/java/teammates/test/pageobjects/StudentProfilePage.java]: Odd, I thought I removed it as the first thing I did, thanks for pointing it out

Comment (MrFool) [inline src/test/java/teammates/test/pageobjects/StudentProfilePage.java]: I remember now, I removed it and did a undo because I wanted to look at the comment and forgot to remove it at the end when I commited it, no wonder the test felt like it was going 5 seconds slower than usual!

**Comment by MrFool** [comment]
Updated it based on the comments.

On a side note, I just ran this version of the test in the entire suite and got it passing in one try on one occasion (466/466), on the other one I managed to get it to pass at (465/466) some InvocationTargetException that is unrelated to this test so I think this solves the problem, at least for now. We can merge this (once it's passed review) and let others run this and see if they still encounter this problem.

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 3]
```diff
@@ -949,6 +949,41 @@ public AppPage verifyStatus(String expectedStatus){
...
+     * load depending on things such as browser type and how an event is triggered.
+     * 
+     * Note that we must wait for the next page's status message to be visible on every try within the while
+     * loop. This is because the previous check might have checked early and have not waited for the page
+     * load to finish. From that, it is possible to create a situation whereby the page has now loaded
+     * on the next try (after 1000ms) and the status message is still loading and still not displayed.
+     * 
+     * @return The app page itself for method chaining flexibility
+     */
+    public AppPage verifyStatusWithRetry(String expectedStatus, int numberOfTries) {
```
Comment (damithc) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: use `maxRetryCount` instead?

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 4]
```diff
@@ -949,6 +949,41 @@ public AppPage verifyStatus(String expectedStatus){
...
+        int tryNumber = 0;
```
Comment (damithc) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: currentRetryCount?

**Comment by MrFool** [comment]
Updated the variable namings
