### PR TITLE
Exception: Cannot read fields from a deleted object #4265

### LINKED ISSUE #4265: Exception: Cannot read fields from a deleted object
Cannot read fields from a deleted object

Request Path /page 
Request Parameters {studentemail::abc@miamioh.edu, submit::Save Changes, teamname::F09, newstudentemail::abc@miamioh.edu, sectionname::FR, user::def@miamioh.edu, studentname::Sam Song, courseid::SOC153DF-fall2015, comments::} 
Stack Trace

javax.jdo.JDOUserException: Cannot read fields from a deleted object
FailedObject:afdfddflYW1tYXRlc3Y0ch0LEhBGZWVkYmFja1F1ZXN0aW9uGICAgNKZ1MgKDA%def@miamioh.edu%abc@miamioh.edu
	at org.datanucleus.jdo.state.PersistentDeleted.transitionReadField(PersistentDeleted.java:115)
	at org.datanucleus.state.AbstractStateManager.transitionReadField(AbstractStateManager.java:561)
	at org.datanucleus.state.JDOStateManagerImpl.isLoaded(JDOStateManagerImpl.java:1900)
	at teammates.storage.entity.FeedbackResponse.jdoGetfeedbackSessionName(FeedbackResponse.java)
	at teammates.storage.entity.FeedbackResponse.getFeedbackSessionName(FeedbackResponse.java:59)
	at teammates.common.datatransfer.FeedbackResponseAttributes.(FeedbackResponseAttributes.java:58)
	at teammates.storage.api.FeedbackResponsesDb.getFeedbackResponsesForReceiverForCourse(FeedbackResponsesDb.java:511)
	at teammates.logic.core.FeedbackResponsesLogic.getFeedbackResponsesForReceiverForCourse(FeedbackResponsesLogic.java:202)
	at teammates.logic.core.FeedbackResponsesLogic.updateFeedbackResponsesForChangingSection(FeedbackResponsesLogic.java:519)
	at teammates.logic.core.StudentsLogic.updateStudentCascade(StudentsLogic.java:249)
	at teammates.logic.core.StudentsLogic.updateStudentCascade(StudentsLogic.java:211)
	at teammates.logic.api.Logic.updateStudent(Logic.java:1163)
	at teammates.ui.controller.InstructorCourseStudentDetailsEditSaveAction.execute(InstructorCourseStudentDetailsEditSaveAction.java:51)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:442)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:234)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #4265

### CODE REVIEW

**Comment by kanghj** [comment]
@imouto1994, help me review this?

**Comment by imouto1994** [comment]
@kanghj Okay working on it :)

File: src/main/java/teammates/storage/api/FeedbackResponsesDb.java [hunk 1]
```diff
@@ -532,7 +534,9 @@ public FeedbackResponse getFeedbackResponseEntityOptimized (FeedbackResponseAttr
                 new ArrayList<FeedbackResponseAttributes>();
         
         for (FeedbackResponse fr : frList) {
+            if (!JDOHelper.isDeleted(fr)) {
```
Comment (imouto1994) [inline src/main/java/teammates/storage/api/FeedbackResponsesDb.java]: Should we have some comments to clarify why we need to check if object is deleted for these 2 functions while other retrieval functions do not have ?

Comment (kanghj) [inline src/main/java/teammates/storage/api/FeedbackResponsesDb.java]: Actually, I think it might make sense to do this check for every database read, but should be discussed and done in another issue if that's the case.

Comment (imouto1994) [inline src/main/java/teammates/storage/api/FeedbackResponsesDb.java]: Ok then :)
