### PR TITLE
Bug in feedback session opening reminder test #4185

### LINKED ISSUE #4185: Bug in feedback session opening reminder test
image
There's no checking whether the session enables opening email or not.
This bug is hidden all these while because the only test that caters to it _gives a false positive_.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4185

### CODE REVIEW

File: src/test/java/teammates/test/automated/FeedbackSessionOpeningReminderTest.java [hunk 1]
```diff
@@ -99,7 +99,8 @@ public void testAdditionOfTaskToTaskQueue() throws Exception {
         
         // Modify session to set emails as unsent but still open
         // by closing and opening the session. Also disable sending
-        // open emails.
+        // open emails, but in the current implementation open emails
```
Comment (kanghj) [inline src/test/java/teammates/test/automated/FeedbackSessionOpeningReminderTest.java]: Would it be better if "current implementation" is removed from the comment? In future, if the implementation gets modified, but this comment isn't modified, then it will be really confusing for a future developer.

Comment (wkurniawan07) [inline src/test/java/teammates/test/automated/FeedbackSessionOpeningReminderTest.java]: Agree, it can be confusing if the implementation is modified but the comment is not. But not including it will make people wonder when they found out that the open emails are still sent, like me yesterday. So it's a trade-off.
