### PR TITLE
AdminActivityLogPageUiTest occasional fails due to IndexOutOfBoundException #3440

### LINKED ISSUE #3440: AdminActivityLogPageUiTest occasional fails due to IndexOutOfBoundException
Fixing what can be fixed.
newtestfailureagain

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3440 
(deleted the old explanation: they're totally off tangent and not addressing the issue).
The fails occur if the log entries are all from test e-mail accounts (ending with .tmt), because they will be _invisible_ in the logs table.

### CODE REVIEW

File: src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java [hunk 1]
```diff
@@ -33,7 +33,12 @@ public String getPersonInfoOfFirstEntry(){
     public void clickViewActionsButtonOfFirstEntry(){
         
         WebElement table = browser.driver.findElement(By.id("logsTable"));
-        WebElement tableRow = table.findElements(By.tagName("tr")).get(1);
+        WebElement tableRow;
+        try {
+            tableRow = table.findElements(By.tagName("tr")).get(1);
+        } catch (IndexOutOfBoundsException onlyoneentry) {
+            tableRow = table.findElements(By.tagName("tr")).get(0);
+        }
```
Comment (damithc) [inline src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java]: Try not to use exceptions to control the normal workflow. may be check the result size first?

Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AdminActivityLogPage.java]: That works too. Updated.

File: src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java [hunk 2]
```diff
@@ -49,7 +49,7 @@ public void testViewActionsLink(){
         
         try {
             String expectedPersonInfo = logPage.getPersonInfoOfFirstEntry();      
-            logPage.clickViewActionsButtonOfFirstEntry();
+            logPage.clickViewActionsButtonOfSecondEntry();
```
Comment (damithc) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java]: The method name matches what the method does?

**Comment by wkurniawan07** [comment]
Uh oh, just got another occurrence of this. Investigating.

**Comment by wkurniawan07** [comment]
Solved it, and I know it is solved because I could replicate the failure at will.

File: src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java [hunk 3]
```diff
@@ -57,6 +57,12 @@ public void testViewActionsLink(){
              * This can happen if this test is run right after the server is started.
              * In this case, no view actions can be done.
              */
+        } catch (IndexOutOfBoundsException invisibletmtlogs) {
+            /*
+             * This can happen if all the log entries are from test accounts
+             * (i.e emails ending with .tmt) because they are invisible.
+             * In this case, no view actions can be done.
+             */
```
Comment (damithc) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java]: Can go ahead and merge. But before that, may be rename the two exceptions to the more conventional names nsee and ioobe? The current names, while more informative, do not match the object type, which can look odd if we decide to do more things with the exception object. For example, `emptylogs.getMessage()` looks misleading because the it is odd to have an exception called `emptylogs`. `excpetionFromEmptyLogs` is more accurate, but a bit long (I don't mind it though). You choose :-)

Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminActivityLogPageUiTest.java]: I would go with the more informative ones, length should not be an issue. Wait a minute.
