### PR TITLE
AdminAccountManagementPageUiTest failing on live server #4356

### LINKED ISSUE #4356: AdminAccountManagementPageUiTest failing on live server
line 53
        loginToAdminAccountsManagementPage();

Selenium timed out.
This page takes very long to load because live server has thousands of accounts.

### PR DESCRIPTION
**Pull request by junhaoyap**
Fixes #4356 

@damithc it 3 minutes good enough, or how long does it take?

### CODE REVIEW

**Comment by damithc** [comment]
A fixed delay is not a good solution. We should wait based on some element in the page.

**Comment by junhaoyap** [comment]
You're right, it seems waitForPageToLoad does an explicit wait and we seem to have that strewn across many places in our application which would be better if converted to implicit waits, I will convert this to an implicit wait and give it a time for 3 minutes, it will return earlier if possible, but please do let me know if 3 minutes is not enough?

**Comment by junhaoyap** [comment]
@kanghj do help me look through when possible :)

**Comment by junhaoyap** [comment]
If this is ok to merge and I'm not available due to time zone differences, do merge it for me before releasing the milestone, it'll help with the live server testing :)

File: src/test/java/teammates/test/cases/ui/browsertests/AdminAccountManagementPageUiTest.java [hunk 1]
```diff
@@ -110,6 +110,14 @@ public void testDeleteInstructorAccountAction(){
     private void loginToAdminAccountsManagementPage() {
         accountsPageUrl = createUrl(Const.ActionURIs.ADMIN_ACCOUNT_MANAGEMENT_PAGE + "?all=true");
         accountsPage = loginAdminToPageForAdminUiTests(browser, accountsPageUrl, AdminAccountManagementPage.class);
+
+        boolean isDevEnvironment = Boolean.parseBoolean(System.getProperty("isDevEnvironment"));
+
+        // On non-dev environments, page can take a long time to load
+        if (!isDevEnvironment) {
```
Comment (kanghj) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminAccountManagementPageUiTest.java]: It should be fine if this is done without checking for the dev environment too right?

File: src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java [hunk 2]
```diff
@@ -92,4 +92,9 @@ public boolean isTableVisible() {
         }
         return result;
     }
+
+    public void waitForPageToFinishLoadingOnNonDevEnvironment() {
+        By currentPageEntryCountSpan = By.id("currentPageEntryCount");
+        waitForElementPresence(currentPageEntryCountSpan, 180);
```
Comment (kanghj) [inline src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java]: 3 minutes might be too large. If I recall correctly, google app engine requests must return in 1 minute otherwise error 500 is returned.

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 3]
```diff
@@ -233,6 +233,17 @@ public void waitForElementPresence(By by){
         WebDriverWait wait = new WebDriverWait(browser.driver, TestProperties.inst().TEST_TIMEOUT);
         wait.until(ExpectedConditions.presenceOfElementLocated(by));
     }
+
+    /**
+     * Waits for the element to appear in the page, up to the timeout specified and can
+     * return early if the expected conditions has happened
+     * @param by
+     * @param timeToImplicitlyWait
```
Comment (kanghj) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: You can mention that timeToImplicitlyWait is in seconds here, or rename the variable.

File: src/test/java/teammates/test/cases/ui/browsertests/AdminAccountManagementPageUiTest.java (hunk 1 above)
Comment (junhaoyap) [inline src/test/java/teammates/test/cases/ui/browsertests/AdminAccountManagementPageUiTest.java]: Nice catch, totally right on now that it's implicit wait

File: src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java (hunk 2 above)
Comment (junhaoyap) [inline src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java]: Hmm ok, means if the loading ever > 1 minute, we need to do it by pagination + AJAX in the future?

File: src/test/java/teammates/test/pageobjects/AppPage.java (hunk 3 above)
Comment (junhaoyap) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: :+1:

**Comment by junhaoyap** [comment]
@kanghj please rereview when possible

File: src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java (hunk 2 above)
Comment (kanghj) [inline src/test/java/teammates/test/pageobjects/AdminAccountManagementPage.java]: Yeah, we might need to make this page use ajax in future.

**Comment by kanghj** [comment]
Looks good to me:+1:

**Comment by junhaoyap** [comment]
Seems like this is slightly late for 5.56, I'll need to open the PRs earlier next time, apologies! Thanks for the review :)

**Comment by junhaoyap** [comment]
Going to add a comment about why there is an extra wait before merging in case someone else is thinking of removing it in the future since it's not the "standard procedure"

**Comment by junhaoyap** [comment]
I mean "master", not "develop"
