### PR TITLE
InstructorFeedbackResultsPage: Incorrect function logic #2956

### LINKED ISSUE #2956: InstructorFeedbackResultsPage: Incorrect function logic
The function, verifyAllResultsPanelBodyVisibility, below does not obtain the DOM elements correctly.
".panel-heading+.panel-body" is invalid and the retrieved webElement colection is always empty.
Therefore, the loop will always be skipped. Thus, the function always return true.

I discovered this when I was running InstructorFeedbackResultPageUiTest where my Javascript was running slower and the verification of the collapsed/expanded panels always fail.

```
public boolean verifyAllResultsPanelBodyVisibility(boolean visible){
        for(WebElement e : browser.driver.findElements(By.cssSelector(".panel-heading+.panel-body"))){
            if(e.isDisplayed() != visible){
                return false;
            }
        }
        return true;
    }

### PR DESCRIPTION
**Pull request by rcyq**
Fixes #2956

### CODE REVIEW

File: src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java [hunk 1]
```diff
@@ -184,7 +184,13 @@ public void editFeedbackResponseComment(String commentIdSuffix, String newCommen
     }
     
     public boolean verifyAllResultsPanelBodyVisibility(boolean visible){
-        for(WebElement e : browser.driver.findElements(By.cssSelector(".panel-heading+.panel-body"))){
+        int numOfQns = browser.driver.findElements(By.cssSelector(".panel-heading+.panel-collapse")).size();
+        assertTrue(numOfQns > 0);
+        
+        // Wait for the total duration according to the number of collapse/expand intervals between questions
+        ThreadHelper.waitFor(numOfQns * 50);
```
Comment (LowWeiLin) [inline src/test/java/teammates/test/pageobjects/InstructorFeedbackResultsPage.java]: i think we might need to add a slightly longer wait. Using the exact timing may still cause failures on slower computers. Maybe +1 second to it?

**Comment by LowWeiLin** [comment]
Looks good to me @damithc
