### PR TITLE
StudentCourseJoinConfirmationPageUiTest fails due to invalid login page #3607

### LINKED ISSUE #3607: StudentCourseJoinConfirmationPageUiTest fails due to invalid login page
Was actually doing God mode refinement on this UI test when suddenly this happened:
scjcbug
Encountered this for a while already but this is the first time I encountered it _in isolation_, which is a good thing since I can now pinpoint the cause exactly.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3607 
This is one of the pages that can be left behind when it fails:
scjcbugexplained
And everything suddenly becomes obvious.

### CODE REVIEW

File: src/test/java/teammates/test/cases/ui/browsertests/StudentCourseJoinConfirmationPageUiTest.java [hunk 1]
```diff
@@ -233,4 +233,14 @@ private LoginPage createCorrectLoginPageType(String pageSource) {
...
     }
+
+    // continuously ask BackDoor to get the key until a legit key is returned
+    private String getKeyFromBackDoor(String courseId, String studentEmail) {
+        String key = "[BACKDOOR_STATUS_FAILURE]";
+        while (key.startsWith("[BACKDOOR_STATUS_FAILURE]")) {
+            key = BackDoor.getKeyForStudent(courseId, studentEmail);
+        }
+        return key;
+    }
```
Comment (damithc) [inline src/test/java/teammates/test/cases/ui/browsertests/StudentCourseJoinConfirmationPageUiTest.java]: `Retry forever` is a bit risky. Limit to a fixed number of tries. Also, use a delay between tries?

Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/browsertests/StudentCourseJoinConfirmationPageUiTest.java]: Added both.
