### PR TITLE
Many test failures on dev server #4443

### LINKED ISSUE #4443: Many test failures on dev server
20+ cases fail on dev server
The diff view shows things like this, which I thought should not show up in diff view any more

image

image

### PR DESCRIPTION
**Pull request by thyageshm**
fixes #4443

### CODE REVIEW

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 1]
```diff
@@ -812,13 +812,13 @@ private static String processPageSourceForGodMode(String content) {
                 .replaceAll(Const.ParamsNames.REGKEY + "%3D([a-zA-Z0-9]){1,}\\%", Const.ParamsNames.REGKEY + "%3D\\${regkey\\.enc}\\%")
                 
                 // maintain order for the two below
-                // questionid
-                .replaceAll("value=\"([a-zA-Z0-9-_]){62,}\"","value=\"\\${question\\.id}\"")
                 // regkey in unreg student page
-                .replaceAll("value=\"([a-zA-Z0-9-_]){50,}\"","value=\"\\${regkey\\.enc}\"")
+                .replaceAll("(type=\"hidden\" ?|name=\""+Const.ParamsNames.REGKEY+"\" ?|value=\"([a-zA-Z0-9-_]){1,}\" ?){3}","name=\""+Const.ParamsNames.REGKEY+"\" type=\"hidden\" value=\"\\${regkey\\.enc}\"")
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: The params are randomized, is it? I thought God mode acts after it's converted to standard HTML, which means the params should've been sorted already.
Also, I think the regex for regkey shouldn't be softened. 50 as before works good. Unless there's a reason?

Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: 1. Godmode runs on the html BEFORE it is standardized. This was done because the standardization process used to sanitize the html and so we decided to run Godmode on the html first before the standardization. 

2. Now that the context is very tight, I though it would be alright to loosen the requirement. I guess 50 is good, but is there a lower number that would be more robust?

**Comment by thyageshm** [comment]
@wkurniawan07 I have updated the length constraint

**Comment by wkurniawan07** [comment]
Looks good! :+1:
