### PR TITLE
Split contents of InstructorFeedbackResultsPageUiTest into 2 sessions #3591

### LINKED ISSUE #3591: Split contents of InstructorFeedbackResultsPageUiTest into 2 sessions
The first session has too many responses now, and our code for verifying html is not working well with that test anymore. Whenever the tests do not match, the tests freezes, making it impossible to use godmode on it.

Part of #3530

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #3591.

Moved some of the questions and responses from the first session into the second session and add html files generated by godmode for the additional comparisons. This adds a little more overhead and will cause the test to slow down a little, but without this, making modifications to the results page was too difficult. This should also allow us to add more questions with different configurations in future.

I've modified some of the existing questions to cover more recipient types, and made some of the givers/recipients of the question to be anonymous. 

@LowWeiLin  have a look?

### CODE REVIEW

File: src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java [hunk 1]
```diff
@@ -120,21 +120,18 @@ public void testSortAction() {
...
-        assertEquals("[more]", resultsPage.getQuestionAdditionalInfoButtonText(9, "giver-1-recipient-1"));
-        assertEquals(true, resultsPage.clickQuestionAdditionalInfoButton(9, "giver-1-recipient-1"));
-        assertEquals("[less]", resultsPage.getQuestionAdditionalInfoButtonText(9, "giver-1-recipient-1"));
-        assertEquals(false, resultsPage.clickQuestionAdditionalInfoButton(9, "giver-1-recipient-1"));
-        assertEquals("[more]", resultsPage.getQuestionAdditionalInfoButtonText(9, "giver-1-recipient-1"));
+        assertEquals("[more]", resultsPage.getQuestionAdditionalInfoButtonText(8, "giver-1-recipient-1"));
+        assertEquals(true, resultsPage.clickQuestionAdditionalInfoButton(8, "giver-1-recipient-1"));
+        assertEquals("[less]", resultsPage.getQuestionAdditionalInfoButtonText(8, "giver-1-recipient-1"));
+        assertEquals(false, resultsPage.clickQuestionAdditionalInfoButton(8, "giver-1-recipient-1"));
+        assertEquals("[more]", resultsPage.getQuestionAdditionalInfoButtonText(8, "giver-1-recipient-1"));
```
Comment (LowWeiLin) [inline src/test/java/teammates/test/cases/ui/browsertests/InstructorFeedbackResultsPageUiTest.java]: These test the javascript to show questionAdditionalInfo is working, testing them once should suffice as they all use the same code.
Testing the content can be a separate, non-UI test.

File: src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html [hunk 2]
```diff
@@ -315,6 +315,7 @@
                 <div class="panel-body">
                 
                         <div class="panel panel-info">
+                            <!--Note: When an element has class text-preserve-space, do not insert and HTML spaces-->
```
Comment (LowWeiLin) [inline src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html]: "do not insert and HTML spaces" What does this mean? Typo?

Comment (kanghj) [inline src/test/resources/pages/instructorFeedbackResultsAjaxByGQR.html]: Typo from #3426
