### PR TITLE
instructor feedback edit: previous values are lost when reporting incorrect end time #3693

### LINKED ISSUE #3693: instructor feedback edit: previous values are lost when reporting incorrect end time
For example, if the end time is earlier than start time, the page is reloaded with the error message, but reverts back to earlier values instead of loading with the values the user was trying to save.

### PR DESCRIPTION
**Pull request by bamboo3250**
Fix #3693
I changed RedirectResult to AjaxResult when submitting the form. When the AjaxResult is returned, it will  show and focus on status message. 

@kanghj Could you review this one?

### CODE REVIEW

File: src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java [hunk 1]
```diff
@@ -52,11 +52,13 @@ protected ActionResult execute() throws EntityDoesNotExistException {
...
                     + "<br><span class=\"bold\">Results visible from:</span> " + feedbackSession.resultsVisibleFromTime
                     + "<br><br><span class=\"bold\">Instructions:</span> " + feedbackSession.instructions;
+            data.setHasError(false);
         } catch (InvalidParametersException e) {
             setStatusForException(e);
+            data.setHasError(true);
         }
-        
-        return createRedirectResult(data.getInstructorFeedbackEditLink(courseId, feedbackSessionName));
+        data.setStatusForAjax(statusToUser.get(0));
```
Comment (kanghj) [inline src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java]: Only displaying the first <code>statusToUser</code> may not be good? We should be able to handle displaying multiple status messages. If the user has and is using multiple tabs on teammates, sometimes the statusMessage may show up in the wrong tab. The code in this action may also in future add multiple status messages.

File: src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html [hunk 2]
```diff
@@ -905,10 +905,7 @@ <h5 class="col-sm-2">
 
 
     
-        <div id="statusMessage" class="alert alert-warning">
-            The feedback session has been updated.
-        </div>
-        <script type="text/javascript" src="/js/statusMessage.js"></script>
+        <div id="statusMessage" style="display: none;"></div>
```
Comment (kanghj) [inline src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html]: ?
What happened to the status message?

File: src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java (hunk 1 above)
Comment (damithc) [inline src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java]: It may be unrelated, but I've noticed even in the original jsp version sometimes the status message shows up in the wrong tab.

File: src/main/webapp/js/instructorFeedbackEdit.js [hunk 3]
```diff
@@ -53,6 +50,42 @@ function readyFeedbackEditPage() {
...
+        event.preventDefault();
+        
+        var $form = $(event.target);
+        // Use Ajax to submit form data
+        $.ajax({
+            url: '/page/instructorFeedbackEditSave',
+            type: 'POST',
+            data: $form.serialize(),
+            beforeSend: function() {
+                $('#statusMessage').hide();
```
Comment (kanghj) [inline src/main/webapp/js/instructorFeedbackEdit.js]: Make a variable for the repeated $('#statusMessage')

File: src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java (hunk 1 above)
Comment (kanghj) [inline src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java]: I believe that's because we store the status messages as an attribute in the HttpSession, which is not specific to just the current action.

File: src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html (hunk 2 above)
Comment (bamboo3250) [inline src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html]: Well, previously the test was redirect result. Now it became ajax result so the content in `textarea` is not updated. So I refresh the page and the statusMessage disappear as a result. You can check the `AdminHomePageUiTest.java`.

File: src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java (hunk 1 above)
Comment (bamboo3250) [inline src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java]: If it's mixed with other tabs' statusMessage, how do we get the exact one?

Comment (kanghj) [inline src/main/java/teammates/ui/controller/InstructorFeedbackEditSaveAction.java]: Maybe for the status messages in this action, there is no need to add them to <code>statusToUser</code> and directly set statusForAjax?

File: src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html (hunk 2 above)
Comment (kanghj) [inline src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html]: Ah, we should still show a status message if the feedback session was successfully modified. Your javascript still focuses the user to the status message (a blank message, in some cases) after editing.

Why is there a need to refresh the page in the test?

Comment (bamboo3250) [inline src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html]: When we edit `textarea`, the content is not updated in html page source so the `verifyMainHtml` will fail. I want to check the new content in `textarea` so I refresh the page in the test before calling `verifyMainHtml`.

**Comment by bamboo3250** [comment]
I fixed according to those suggestions above.

File: src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html (hunk 2 above)
Comment (kanghj) [inline src/test/resources/pages/newlyJoinedInstructorFeedbackSessionSuccessEdited.html]: Ok, then won't that mean that the page should be refreshed before verifying <code>instructorFeedbackEditSuccess.html</code> too?
