### PR TITLE
InstructorHomePageUiTest sometimes fails at line 400 #4685

### LINKED ISSUE #4685: InstructorHomePageUiTest sometimes fails at line 400
```
homePage.verifyStatus(Const.StatusMessages.FEEDBACK_SESSION_COPIED);
```

```
homePage.clickFsCopySubmitButton();
```
This function needs to have a waitForPageToLoad() at the end.

### PR DESCRIPTION
**Pull request by kennho**
Fixes #4685

### CODE REVIEW

File: src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java [hunk 1]
```diff
@@ -396,7 +396,7 @@ public void testCopyToFsAction() throws Exception {
         homePage.fillCopyToOtherCoursesForm("New name!");
         
         homePage.clickFsCopySubmitButton();
-        
+        homePage.waitForPageToLoad();
```
Comment (LowWeiLin) [inline src/test/java/teammates/test/cases/ui/browsertests/InstructorHomePageUiTest.java]: Do the wait inside clickFsCopySubmitButton? Then there will be no need for developers to remember it every time clickFsCopySubmitButton is used.

**Comment by kennho** [comment]
updated
