### PR TITLE
instructorSessionResults: there is no way to recover from failed ajax calls #4276

### LINKED ISSUE #4276: instructorSessionResults: there is no way to recover from failed ajax calls
In the per question view (may be applicable to other views too), if there are many ajax calls started automatically (e.g. 20 questions, 80 students), some of the ajax loader gifs will keep on going. I suppose those ajax calls failed for some reason (the logs say 'API failed to complete'). There is no way for the instructor to recover. 
Actually, the instructor can recover by clicking those panels again, but the user will not know that because the ajax loader is still going on.

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #4276

The "The results is too large to be viewed. Please choose to view the results by questions or download the results." might be affected because of #4184, where the error code returned by the page now (correctly) triggers the error callback instead of the success callback. We already have an issue for that message, will try to fix that soon.

### CODE REVIEW

File: src/main/webapp/js/instructorFeedbackResultsAjaxByGQR.js [hunk 1]
```diff
@@ -25,7 +25,13 @@ $(document).ready(function() {
...
             },
             error: function() {
-
+                var ajaxErrorStart = '<div class="ajax-error">';
+                var warningSign = '<span class="glyphicon glyphicon-warning-sign"></span>';
+                var errorMsg = '[ Failed to load. Click here to retry. ]';
+                errorMsg = '<strong style="margin-left: 1em; margin-right: 1em;">' + errorMsg + '</strong>';
+                var chevronDown = '<span class="glyphicon glyphicon-chevron-down"></span>';
+                var ajaxErrorEnd = '</div>';
+                displayIcon.html(ajaxErrorStart + warningSign + errorMsg + chevronDown + ajaxErrorEnd);
```
Comment (damithc) [inline src/main/webapp/js/instructorFeedbackResultsAjaxByGQR.js]: Looks this piece of code is repeated in a few pages. Any way to abstract it out?

**Comment by kanghj** [comment]
Changes made. @LowWeiLin

File: src/main/webapp/js/instructor.js [hunk 2]
```diff
@@ -154,6 +154,22 @@ function setupFsCopyModal() {
     });
 }
 
+// For ajax failure handling
+
+/**
+ * Given an element, replaces the HTML content of the element with an error message prompting 
+ * the user to retry.
+ */
+function displayAjaxRetryMessage($element) {
```
Comment (LowWeiLin) [inline src/main/webapp/js/instructor.js]: The function name can be more specific, since this particular error message is only used in panels/feedback results. It probably can't be used for ajax calls elsewhere.

Comment (kanghj) [inline src/main/webapp/js/instructor.js]: Moved into instructorFeedbackResults.js. Was initially thinking that the function could be reused elsewhere, to standardize error handling for the different pages that involve ajax requests by clicking on a panel header.

File: src/main/webapp/js/instructorFeedbackResultsAjaxResponseRate.js [hunk 3]
```diff
@@ -20,7 +20,7 @@ $(document).ready(function() {
                 // submitButton.html('<img src="/images/ajax-loader.gif">');
             },
             error: function() {
-
+                displayAjaxRetryMessageForPanelHeading(displayIcon);
```
Comment (LowWeiLin) [inline src/main/webapp/js/instructorFeedbackResultsAjaxResponseRate.js]: Any tests for this?

Comment (kanghj) [inline src/main/webapp/js/instructorFeedbackResultsAjaxResponseRate.js]: Added

**Comment by LowWeiLin** [comment]
:thumbsup: Can merge.
