### PR TITLE
Not enough info in 'severe error log compilation' email #4703

### LINKED ISSUE #4557: Severe log without enough details
Here's an example. May be include stacktrace?
Error Message: teammates.logic.core.Emails sendErrorReport: Error in sending crash report:

### LINKED ISSUE #4703: Not enough info in 'severe error log complilation' email
For 'deadline exceeded' exceptions, what I get is something like this:
image

The error in the GAE log looks like this:
image

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #4703, fixes #4557 (two duplicate issues)
`sendLogReport` is in particular problematic because the variable `email` appears out of nowhere and makes everything null. Somebody should've copy-pasted it from `sendErrorReport` :p

### CODE REVIEW

File: src/main/java/teammates/logic/core/Emails.java [hunk 1]
```diff
@@ -806,23 +805,24 @@ public MimeMessage sendErrorReport(HttpServletRequest req, Throwable error) {
...
         } catch (Exception e) {
-            log.severe("Error in sending log report: "
-                    + (email == null ? "" : email.toString()));
+            logErrorInSendingItem("log report", message, e);
         }
+        return message;
+    }
     
-        return email;
+    private static void logErrorInSendingItem(String itemType, MimeMessage message, Exception e) {
```
Comment (thyageshm) [inline src/main/java/teammates/logic/core/Emails.java]: any reason why it is static?

**Comment by thyageshm** [comment]
everything is fine. just one clarification and then we can change the status to toMerge

File: src/main/java/teammates/logic/core/Emails.java (hunk 1 above)
Comment (damithc) [inline src/main/java/teammates/logic/core/Emails.java]: Add a header comment too.

Comment (wkurniawan07) [inline src/main/java/teammates/logic/core/Emails.java]: This is a private method, and I can't really think of a comment that doesn't touch the "how" part of the method. The best I can think of is "Logs that sending message is failed due to exception ...", but that should've been inferred from the method name.

Comment (damithc) [inline src/main/java/teammates/logic/core/Emails.java]: The `severe` part is important. The purpose of this logging is to let it be picked up by periodic severe log alerts. Either add a comment or rename to mention severe.

**Comment by wkurniawan07** [comment]
Changed the method name to mention "severe", and made it non-static.

**Comment by thyageshm** [comment]
@damithc, ready for your review
