### PR TITLE
(URGENT) Fix for #3346 breaks TableSortTest #3468

### LINKED ISSUE #3468: (URGENT) Fix for #3346 breaks TableSortTest
Introduced in #3466
Apparently .innerText doesn't work in Firefox, but works in Chrome.
An alternative method that works in Firefox is available (and still achieves the objective), which will be pushed in less than 2 mins. Dev green confirmed.

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3468 
My bad for not ensuring dev green when merging #3466 before. It is dev green this time.

### CODE REVIEW

File: src/main/webapp/js/common.js [hunk 1]
```diff
@@ -189,7 +189,7 @@ function sortTable(oneOfTableCell, colIdx, comparator, ascending, row) {
             continue;
         }
         
-        var innerText = $RowList[i].cells[colIdx - 1].innerText;
+        var innerText = $.trim(jQuery($RowList[i].cells[colIdx - 1]).text());
```
Comment (kanghj) [inline src/main/webapp/js/common.js]: Add a comment
