### PR TITLE
StudentFeedbackSubmitPageUiTest is failing due to MOTD #4087

### LINKED ISSUE #4087: StudentFeedbackSubmitPageUiTest is failing due to MOTD
Reproduce by changing the motd property in the build.properties

### PR DESCRIPTION
**Pull request by taniach**
Fixes #4087

### CODE REVIEW

File: src/test/java/teammates/test/driver/HtmlHelper.java [hunk 1]
```diff
@@ -224,7 +224,22 @@ private static boolean isToolTip(Node currentNode) {
     
     private static boolean isMotdComponent(Node currentNode) {      
         if (currentNode.getNodeName().equalsIgnoreCase("script")) {
-            return currentNode.getTextContent().contains("closeMotd");
+            NamedNodeMap attributes = currentNode.getAttributes();
+            
+            if (attributes != null) { 
+                for (int i = 0; i < attributes.getLength(); i++) {
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/driver/HtmlHelper.java]: Will `for (Node attribute : attributes)` work here?

Comment (taniach) [inline src/test/java/teammates/test/driver/HtmlHelper.java]: Can only iterate over an array or an instance of java.lang.Iterable
