### PR TITLE
FeedbackRubricQuestionUiTest failing on live server #3640

### LINKED ISSUE #3640: FeedbackRubricQuestionUiTest failing on live server
Failing at 
`143: submitPage.verifyHtmlMainContent("/studentFeedbackSubmitPageRubricSuccess.html");`

### PR DESCRIPTION
**Pull request by JosephineKwa**
Fixes #3640

### CODE REVIEW

**Comment by JosephineKwa** [comment]
I'm not exactly sure what's causing the cell-hover to appear, perhaps this could serve as a quick fix. After the quick fix, If the test pauses at line 150, you could un-hover the cell by moving your cursor over and off it.

**Comment by JosephineKwa** [comment]
@LowWeiLin for your review :)

File: src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java [hunk 1]
```diff
@@ -125,4 +125,8 @@ public void linkOnCommentsLink() {
         AppPage.getNewPageInstance(browser, StudentCommentsPage.class);
         
     }
+    
+    public void waitForCellHoverToDisappear() {
+        waitForElementToDisappear(By.className("cell-hover"));
```
Comment (LowWeiLin) [inline src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java]: I don't think this works? The element with the "cell-hover" class never disappears, it is the "cell-hover" class that is removed from the element.

Comment (LowWeiLin) [inline src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java]: I cannot replicate the test failure right now though, so I cannot be 100% sure this does not work.
It seems that selenium may randomly hover over the elements triggering the failure?
One possible solution I can think of is to forcefully remove the cell-hover classes using selenium or JavascriptExecutor, since we are not testing the hover behaviors. Might not be a good idea though...
@kanghj What do you suggest?

Comment (kanghj) [inline src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java]: Rather than removing the class, I think we could try adding code to hover over a specific cell with Selenium. We should test that cell-hover class appears when the cells are moused over, unless it's too hard to do so?

Comment (JosephineKwa) [inline src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java]: Hmm, I was assuming it works by polling to see if the element with the class `cell-hover` is visible/present on the page. If the `cell-hover` class is removed from the element, then there no longer exists an element on the page with a `cell-hover` class, so essentially it "disappears".

Comment (JosephineKwa) [inline src/test/java/teammates/test/pageobjects/FeedbackSubmitPage.java]: I did manually test to see if it works by stepping through the code though. I added a break point at line 150 and added the `cell-hover` class to the element before resuming the test. The test paused, so I hovered over and off the cell to remove `cell-hover`, and the test then proceeded.
