### PR TITLE
Numerical scale question bug #3164

### LINKED ISSUE #3164: Numerical scale question bug
When the increment scale is in 2 decimal places, or more...

numericalbug1

Upon saving, will become:

numericalbug2

What's worse is when a student tries to complete it...

numericalbug3

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3164

### CODE REVIEW

**Comment by wkurniawan07** [comment]
Instructor's side:




Student's side:

**Comment by damithc** [comment]
@ackoroa can you review this one?

**Comment by ackoroa** [comment]
I can only do this after my FYP is out of the way (2nd week April) is that ok?

**Comment by damithc** [comment]
@kanghj can you review this?

**Comment by damithc** [comment]
No worries @ackoroa I'll get someone else to give it a try.

File: src/main/webapp/js/instructorFeedbackEdit.js [hunk 1]
```diff
@@ -953,8 +957,8 @@ function updateNumScalePossibleValues(questionNumber) {
         $("#maxScaleBox"+idSuffix).val(max);
     }
     
-    if (step < 0.001) {
-        step = 0.001;
+    if (getFractionPart(step) < 0.001 && getFractionPart(step) != 0) {
```
Comment (kanghj) [inline src/main/webapp/js/instructorFeedbackEdit.js]: This looks like it's for restricting values with more than 3 decimal places, but does not seem like the right way of doing so. For example, if given "0.1001", this check will fail to detect that, because 0.1001 > 0.001, right? The original code also has this problem.

Comment (wkurniawan07) [inline src/main/webapp/js/instructorFeedbackEdit.js]: Oops. Looks like I solved one problem but not another.

Comment (wkurniawan07) [inline src/main/webapp/js/instructorFeedbackEdit.js]: Found a workaround. Will push once dev green.

**Comment by wkurniawan07** [comment]
@kanghj fixed!

**Comment by kanghj** [comment]
Looks good to merge.

**Comment by damithc** [comment]
@LowWeiLin one quick look before @kanghj merge?

**Comment by LowWeiLin** [comment]
Looks correct, can you also add/modify a test case for this?

**Comment by wkurniawan07** [comment]
Only isMoreThanThreeDp is testable. I can add test cases for it, shouldn't take long.

**Comment by wkurniawan07** [comment]
@kanghj @LowWeiLin ready for review again. I hope it's merge-ready now :smiley:

**Comment by LowWeiLin** [comment]
@wkurniawan07 Good to see the JS test, but I was referring to adding UI tests for NUMSCALE questions where the dp of the step is tested. See InstructorFeedbackEditPageUiTest

**Comment by damithc** [comment]
Ideally, update the UI test so that it fails without this bug fix but passes after the fix is applied. In fact the first step of fixing a bug is to modify the test to make it fail (i.e. make the test catch the bug first before fixing the bug).

**Comment by wkurniawan07** [comment]
:sweat_smile: I'm not that used to test-driven development yet. In any case, UI test cases are up.

File: src/main/webapp/js/instructorFeedbackEdit.js [hunk 2]
```diff
@@ -953,11 +957,15 @@ function updateNumScalePossibleValues(questionNumber) {
...
-    if (step < 0.001) {
+    step = roundToThreeDp(step);
+    if (step == 0) {
         step = 0.001;
-        $("#stepBox"+idSuffix).val(step);
     }
-    
+    $("#stepBox" + idSuffix).val(step);        
+    if (isNaN(step)) {
+        $("#stepBox" + idSuffix).val("");
```
Comment (LowWeiLin) [inline src/main/webapp/js/instructorFeedbackEdit.js]: Set to 1 by default, instead of setting it empty?

Comment (wkurniawan07) [inline src/main/webapp/js/instructorFeedbackEdit.js]: Hmmm if I do that then this line in the test page:
```
feedbackEditPage.fillStepNumScaleBox("", -1);
```
Will result in the box filled with 1 instead of being cleared. Not that it's test-breaking, just counter-intuitive.
Also, this extension is only applicable for the test page. For the user, their input is already limited to numbers only, so it won't ever be NaN.

Comment (LowWeiLin) [inline src/main/webapp/js/instructorFeedbackEdit.js]: Ah okay. The code looks good, just need to make sure the tests will fail without the fix, as mentioned by @damithc

Comment (wkurniawan07) [inline src/main/webapp/js/instructorFeedbackEdit.js]: I cherry-picked the changes I made to the test cases to master. As expected, this happened.
expectedfail
