### PR TITLE
StudentCourseJoinConfirmationPageUiTest failing on live server #4354 and InstructorFeedbackEditCopyUiTest failing on live server #4355

### LINKED ISSUE #4354: StudentCourseJoinConfirmationPageUiTest failing on live server
confirmationPage.verifyHtml("/studentCourseJoinConfirmationHTML.html");

image

### LINKED ISSUE #4355: InstructorFeedbackEditCopyUiTest failing on live server
line 45
        feedbackEditPage.verifyHtmlMainContent("/instructorFeedbackEditCopyPage.html");
image

### PR DESCRIPTION
**Pull request by thyageshm**
Fixes #4354 and fixes #4355 
It is a combined pull request as both are related

### CODE REVIEW

**Comment by thyageshm** [comment]
@wkurniawan07 I guess you are the best person to review this pr :-)

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 1]
```diff
@@ -770,9 +770,12 @@ private static String processPageSourceForGodMode(String content) {
         return content
                 .replaceAll("<#comment[ ]*</#comment>", "<!---->")
                 .replace(Config.APP_URL, "${app.url}")
-                .replace("http://localhost:8888", "${web.url}")
-                .replace(Config.APP_URL.replace("http", "https"), "${web.url}")
-                .replace("\"/_ah", "\"${web.url}/_ah")
+                .replace(TestProperties.inst().TEAMMATES_URL, "${test.url}")
+                .replace(TestProperties.inst().TEAMMATES_URL.replace("http", "https"), "${test.url}")
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Is this really needed? As in the part with `.replace("http", "https")`.

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 2]
```diff
@@ -770,9 +770,12 @@ private static String processPageSourceForGodMode(String content) {
...
+                // this is to handle dev server case where url is relative
+                .replace("\"/_ah", "\"${test.url}/_ah")
+                // this handles the logout url that google generates
+                .replaceAll("_ah/logout\\?continue=.*?\"", "_ah/logout?continue={*}\"")
```
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Can we combine these two? Something like
`.replaceAll("\"/_ah/logout\\?continue=.*?\"", "\"${test.url}/_ah/logout?continue={*}\"")`.

**Comment by wkurniawan07** [comment]
And one last thing, I think this can still be two different PRs. The ones involving `/_ah/` for #4354 and the ones involving `${test.url}` for #4355. It's true that they will be conflicting in `studentCourseJoinConfirmationHTML.html` but I guess it's a small price? :p

File: src/test/java/teammates/test/pageobjects/AppPage.java (hunk 1 above)
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: yup, in one case they use javascript to get the page url which returns the https version rather than http version

File: src/test/java/teammates/test/pageobjects/AppPage.java (hunk 2 above)
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: in the staging server, we have the test.url added to the start of /_ah/logout. So I first handle the case for dev server where no such prefix exists. Then handle the general case of the "continue" part in the url

**Comment by thyageshm** [comment]
Since the fixes were small and just to ensure that a complete fix is submitted for both cases I combined them :-P

**Comment by wkurniawan07** [comment]
Alright, all explanations are adequate :-)
Can merge with one minor improvement: I believe this line in God mode (line 791) is no longer needed:
```
.replaceAll(Const.ParamsNames.REGKEY + "%3D([a-zA-Z0-9]){1,}\\%", Const.ParamsNames.REGKEY + "%3D{*}\\%")
```

**Comment by thyageshm** [comment]
Hey I am afraid that change is not relevant to this issue. Any ideas which pr rendered that line useless?

**Comment by thyageshm** [comment]
actually if we are 100% sure that the line is not affecting anything, then we can open a first-timers issue for it :-) I think it is a perfect low-priority (since it technically dead-code) task.

**Comment by wkurniawan07** [comment]
It's this line of this PR:
```
.replaceAll("_ah/logout\\?continue=.*?\"", "_ah/logout?continue={*}\"")
```
The only instance of the regkey regex with `%3D` in all test files is in `studentCourseJoinConfirmationHTML.html` and it has been taken over by the above. That's why I advise to get rid of it here.

**Comment by thyageshm** [comment]
oh! I get what you mean now... haha. Its alright I guess, we can just open a firstTimers issue for it. Let me open one now
