### PR TITLE
InstructorFeedbackEditCopyUiTest failing due to hardcoded localhost:8888 #4311

### LINKED ISSUE #4311: InstructorFeedbackEditCopyUiTest failing due to hardcoded localhost:8888
image

### PR DESCRIPTION
**Pull request by thyageshm**
fixes #4311

### CODE REVIEW

**Comment by LowWeiLin** [comment]
Any changes needed for godmode tests?

**Comment by thyageshm** [comment]
have added more tests :)

**Comment by wkurniawan07** [comment]
With all due respect, I think the fix done in this PR is not necessary at all, or I need some explanation on why they are added.
I can say this because I just tried regenerating the whole test file with God mode again, without the fixes added here, reverting `${web.url}` as necessary, and no `localhost:8888` doesn't appear anywhere.
In fact, this fix adds more question than answer:
- `actual = processPageSourceForGodMode(actual);` in three places: what for?
- `.replace("http://localhost:8888", "${web.url}")`: isn't this what the line `.replace(Config.APP_URL, "${app.url}")` does? Worse, we're adding one new variable `${web.url}` here.
- `.replace("\"/_ah", "\"${web.url}/_ah")`: what for?

**Comment by thyageshm** [comment]
Hi, good to know that you have read deeply into the pull request :-) Let me try and answer your questions. I do concede that one of the things I did in this pr is wrong ( will fix it in #4355  and #4354).
I will comment directly on the code

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 1]
```diff
@@ -698,7 +698,7 @@ public AppPage verifyHtml(String filePath) {
             filePath = TestProperties.TEST_PAGES_FOLDER + filePath;
         }
         String actual = getPageSource();
-        
+        actual = processPageSourceForGodMode(actual);
```
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Since the url is different in dev and staging, we have to substitute the url to something standard before we can compare it with the expected html. So we convert "http://localhost:8888" and "https://<version>-dot-teammatesv4.appspot.com" to "${web.url}" before comparing. To do this, the general way would be to simply pass the actual html through the "processPageSourceForGodMode" method.

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 2]
```diff
@@ -749,6 +749,9 @@ private static String processPageSourceForGodMode(String content) {
         return content
                 .replaceAll("<#comment[ ]*</#comment>", "<!---->")
                 .replace(Config.APP_URL, "${app.url}")
+                .replace("http://localhost:8888", "${web.url}")
+                .replace(Config.APP_URL.replace("http", "https"), "${web.url}")
+                .replace("\"/_ah", "\"${web.url}/_ah")
```
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: "_ah/" happens in dev while the complete url is shown in the staging server's logout link. However, since most of us fix html tests in dev server, we only see "_ah/" in the links (explains why you did not see the "${web.url}" happen when you reloaded the html else where)

File: src/test/resources/pages/adminEmailCompose.html [hunk 3]
```diff
@@ -27,7 +27,7 @@
          </script>
          <script src="/tinymce/js/tinymce/tinymce.min.js" type="text/javascript">
          </script>
-         <link href="http://localhost:8888/tinymce/js/tinymce/skins/lightgray/skin.min.css" rel="stylesheet"/>
```
Comment (thyageshm) [inline src/test/resources/pages/adminEmailCompose.html]: I agree that this one is redundant. But the fact that this was in the generated html means that it is possible to happen again. So for defensive coding, we handle this situation

File: src/test/resources/pages/instructorFeedbackEditCopyPage.html [hunk 4]
```diff
@@ -771,7 +771,7 @@ <h4 class="modal-title">
                         </div>
                         <input name="courseid" type="hidden" value="FeedbackEditCopy.CS2104"/>
                                                 <input name="fsname" type="hidden" value="First Session"/>
-                                                <input name="currentPage" type="hidden" value="http://localhost:8888/page/instructorFeedbackEditPage?user=FeedbackEditCopyinstructor&courseid=FeedbackEditCopy.CS2104&fsname=First+Session"/>
```
Comment (thyageshm) [inline src/test/resources/pages/instructorFeedbackEditCopyPage.html]: This was the reason #4311 was opened

File: src/test/resources/pages/studentCourseJoinConfirmationHTML.html [hunk 5]
```diff
@@ -106,7 +106,7 @@
                      .
                      <br/>
                                           If this is not you please
-                     <a href="/_ah/logout?continue=%2Fpage%2FstudentCourseJoinAuthenticated%3Fkey%3D{*}%26next%3D%2Fpage%2FstudentHomePage">
```
Comment (thyageshm) [inline src/test/resources/pages/studentCourseJoinConfirmationHTML.html]: This handles the difference in the urls generated in dev and staging servers. in staging the entire app url is shown

**Comment by thyageshm** [comment]
Hope the comments above answer your questions. I am planning to do away with ${web.url} and call it ${test.url} since the urls that appear come from the test.properties file under the variable named test.url (something like that)

File: src/test/java/teammates/test/pageobjects/AppPage.java (hunk 1 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Hmmmm but why is this necessary? Is this for the `/_ah` case?

File: src/test/java/teammates/test/pageobjects/AppPage.java (hunk 2 above)
Comment (wkurniawan07) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Ah this is one of the things that God mode didn't regenerate correctly previously. Good that it's solved!

File: src/test/resources/pages/adminEmailCompose.html (hunk 3 above)
Comment (wkurniawan07) [inline src/test/resources/pages/adminEmailCompose.html]: Any possible reason why the localhost is not replaced? I run God mode as mentioned before and it got replaced by `${app.url}` as expected.

Comment (thyageshm) [inline src/test/resources/pages/adminEmailCompose.html]: It only happens once you stage the app on your own server. The app.url variable is defined in the web.xml file and is the server to which you will stage your app. Since many of us do not do the staging, the url in app.url is localhost and hence in your case it has been subsituted by ${app.url} by godmode

File: src/test/java/teammates/test/pageobjects/AppPage.java (hunk 1 above)
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: yup mainly for that case. But also moving forward we are planning to change all the comparisons from regex to normal string comparison. This can only be done if the actual html is processed

**Comment by wkurniawan07** [comment]
I might be wrong, but I think I see a bigger problem here. Is `.replace(Config.APP_URL, "${app.url}")` really the correct way to replace URLs instead of `.replace(TestProperties.inst().TEAMMATES_URL, "${app.url}")`?

**Comment by thyageshm** [comment]
APP_URL is used in the main application code to refer to our application's url (constant for all developers). This need not necessarily be the same as the URL defined in the test.properties file which denotes the server to which we are deploying the app (each developer can have his own staging server to test the code against).

File: src/test/resources/pages/adminEmailCompose.html (hunk 3 above)
Comment (wkurniawan07) [inline src/test/resources/pages/adminEmailCompose.html]: I have to disagree here. This missing replacement is possible if `app.url` does not match `TestProperties.inst().TEAMMATES_URL` because the tinymce link starts with the latter URL.
I'm ready to be proven wrong, but I think the only feasible solution here is for both URLs to be the same whenever God mode needs to be run. The explicit localhost:8888 replacement in God mode is certainly not needed.

**Comment by wkurniawan07** [comment]
Ah, that's true. Anyway I've found another problem that I think is only solvable by matching `app.url` and `TestProperties.inst().TEAMMATES_URL`.

File: src/test/resources/pages/adminEmailCompose.html (hunk 3 above)
Comment (thyageshm) [inline src/test/resources/pages/adminEmailCompose.html]: I am sorry, I said it wrong... it replaces it by app.url in your case because the app.url value in web.xml and test.url in test.properties are the same. In general they dont have to be the same.

Comment (wkurniawan07) [inline src/test/resources/pages/adminEmailCompose.html]: I was wrong as well. In fact, they both have to be different for God mode to work because there are two different URLs to be used. Perhaps this should be checked as well along with the `areTestAccountDefaultValues()`?
So yeah certainly the explicit localhost:8888 replace is not needed. Rather it should be `TestProperties.inst().TEAMMATES_URL` to be replaced with `${web.url}` or whatever variable name, but I'm pretty sure you've figured this out already :-)

Comment (thyageshm) [inline src/test/resources/pages/adminEmailCompose.html]: Yup thanks! will be doing that in #4355. Btw, could you open an issue to update "areTestAccountDefaultValues()"? thanks!
