### PR TITLE
InstructorCommentsPageUiTest failing on live server #4159

### LINKED ISSUE #4159: InstructorCommentsPageUiTest failing on live server
failing on line `219 commentsPage.clickResponseCommentEdit(1, 1, 1, 1);`

### PR DESCRIPTION
**Pull request by JosephineKwa**
Fixes #4159 

I realised this issue had been fixed in PR #4287 , however the test was failing again when I tried running it again this time round. Specifically, on lines 121 and 230. Both were due to ajax elements not completely loading before verification.

### CODE REVIEW

File: src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java [hunk 1]
```diff
@@ -31,7 +31,7 @@ public void loadResponseComments() throws Exception{
         browser.driver.findElement(By.xpath("//*[@id=\"panel_display-2\"]/div/div[1]")).click();
         waitForPageToLoad();
         try{
-            waitForElementPresence(By.xpath("//*[@id=\"panel_display-2\"]/div/div[2]/div[1]/div"));
+            waitForElementVisibility(browser.driver.findElement(By.xpath("//*[@id=\"panel_display-2\"]/div/div[2]/div[1]/div")));
```
Comment (kanghj) [inline src/test/java/teammates/test/pageobjects/InstructorCommentsPage.java]: It's not really related to your pr, but is it possible to improve on the selector, or introduce a variable or comment to explain it? It's hard to figure out what <code>[@id=\"panel_display-2\"]/div/div[2]/div[1]/div"</code> is. We can do this in a new issue.

**Comment by JosephineKwa** [comment]
I'll do it in another issue. Ill extract the rest of the strings in the test as well :)
