### PR TITLE
AllAccessControlUiTest failing due to hardcoded feedback entries submitted #4316

### LINKED ISSUE #4316: AllAccessControlUiTest failing due to hardcoded feedback entries submitted
The last couple of commits affecting [login.html](https://github.com/TEAMMATES/repo/blob/master/src/test/resources/pages/login.html) (b099b5c50c9b5a1ccf8eef446fbb5f44013bc694 and 1357e98) changed the value for "feedback entries submitted so far" from `{*}` to some integer.
Changing the integer back to `{*}` allows the test to pass.

@thyageshm, should this be usually handled by godmode or manually?

### PR DESCRIPTION
**Pull request by junhaoyap**
Fixes #4316

### CODE REVIEW

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 1]
```diff
@@ -746,65 +748,68 @@ public static String processPageSourceForFailureCase(String content) {
...
+            // jQuery local
+            .replace("/js/lib/jquery.min.js", "{*}/jquery.min.js")
+            // jQuery CDN
+            .replace("https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js", "{*}/jquery.min.js")
+            // jQuery-ui local
+            .replace("/js/lib/jquery-ui.min.js", "{*}/jquery-ui.min.js")
+            // jQuery-ui CDN
+            //<script[^>]*>(.*?)</script>
+            .replace("https://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/jquery-ui.min.js", "{*}/jquery-ui.min.js");
+        Pattern p = Pattern.compile("<span class=\"submissionsNumber\".*?</span>", Pattern.DOTALL);
```
Comment (junhaoyap) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Here is the meaty part, the rest are diff-ed by indentation changes since return is moved down here, can ignore everything above Pattern p.

**Comment by junhaoyap** [comment]
@thyageshm please help to review, I think you're the most comfortable with regex and godmode :+1:

File: src/test/java/teammates/test/pageobjects/AppPage.java (hunk 1 above)
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: hey could we continue to use the same pattern as the code above? like do '.replaceAll("<span class=\"submissionsNumber\" id="...">[0-9]+</span>", "....."); '?

Comment (junhaoyap) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: I will try it later, last I tried it doesn't work but maybe I was tired and perhaps I did it wrongly, I'll let you know if it works :)

**Comment by junhaoyap** [comment]
@thyageshm done, I didn't know about the (?s) flag, now I do :)

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 2]
```diff
@@ -797,6 +799,8 @@ private static String processPageSourceForGodMode(String content) {
                 .replaceAll(new SimpleDateFormat("EEE, dd MMM yyyy, ").format(now) + "[0-9]{2}:[0-9]{2}", "{*}")
                 // now (used in comments last edited date) e.g. [Thu May 07 07:52:13 UTC 2015]
                 .replaceAll(new SimpleDateFormat("EEE MMM dd ").format(now) + "[0-9]{2}:[0-9]{2}:[0-9]{2} UTC [0-9]{4}", "{*}")
+                // dynamic feedback submission numbers
+                .replaceAll("(?s)<span class=\"submissionsNumber\".*?</span>", "<span class=\"submissionsNumber\" id=\"submissionsNumber\">{*}</span>")
```
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: I am not sure, but do you think by specifying "[0-9]+,[0-9]+" instead of ".*?" the comparison would be faster?

Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: maybe "[0-9]+ (,[0-9]{3})+"

Comment (junhaoyap) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Yes it will be faster, but perhaps speed is not as important here as the stability of god mode?

Perhaps that can break something else without us knowing, for example any developer who comes on board can display numbers or eventually we can have a page that displays numbers as such "1,234,567" and they will get replaced by god mode and the developer will be left wondering why and unless the developer knows about this specific line, they will never know what's biting them?

Also, it seems god mode is inconsistent and sometimes write things as one line and sometimes as multiple lines, the reason why we need the dot all comparison is because it is being written as multiple lines by god mode and the dot all comparison is what is able to do the multiline HTML element recognition.. without it, I haven't been able to consistently recognize the correct HTML element

Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: ok!

File: src/test/java/teammates/test/pageobjects/AppPage.java [hunk 3]
```diff
@@ -11,6 +11,8 @@
 import java.util.Date;
 import java.util.List;
 import java.util.logging.Logger;
+import java.util.regex.Matcher;
+import java.util.regex.Pattern;
```
Comment (thyageshm) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: these can be removed right?

**Comment by thyageshm** [comment]
once you make the final changes, add modify GodModeTest to handle this new case and you can merge :)

File: src/test/java/teammates/test/pageobjects/AppPage.java (hunk 3 above)
Comment (junhaoyap) [inline src/test/java/teammates/test/pageobjects/AppPage.java]: Ahhh, good catch, I forgot to remove after changing the replacement! I'll fix that soon :)

**Comment by junhaoyap** [comment]
@thyageshm do review one last time! :)

**Comment by thyageshm** [comment]
looks good! merge from master into your branch first cos godmode tests have been modified recently and you can merge back after you resolve any conflicts :-)

**Comment by junhaoyap** [comment]
Nice, thanks, I'll merge it with the logging one when I wake up if it's been reviewed so I only have to run the tests once, surprisingly no conflicts so all good!
