### PR TITLE
Test failing in instructorCoursesPageUiTest #3315

### LINKED ISSUE #3315: Test failing in instructorCoursesPageUiTest
screen shot 2015-04-13 at 1 12 21 pm

anyone else or just me?

### PR DESCRIPTION
**Pull request by wkurniawan07**
Fixes #3315

The root cause of this issue is this action in line 217:
`coursesPage.addCourse(validCourse.id, validCourse.name);`
Of course this action is perfectly valid. The trouble, however, comes if this test fails due to any reason after that action is successfully executed, but before we reach the testDeleteAction() part.
_Because there is no BackDoor operation to delete the course._
As such, any subsequent re-run of the test will result in:

And this fails the comparison in line 128.

### CODE REVIEW

File: src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java [hunk 1]
```diff
@@ -65,6 +67,13 @@ public static void classSetup() throws Exception {
         
         /* Explanation: Gets a browser instance to be used for this class. */
         browser = BrowserPool.getBrowser();
+        
+        /* 
+         * Any entity that is created in previous test run must be deleted.
+         * If that previous test run fails, the entity persists and that will
+         * break tests.
+         */
+        BackDoor.deleteCourse(validCourse.id); // delete if it exists
```
Comment (LowWeiLin) [inline src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java]: Why does moving the code up here make it work?

Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java]: Consider the condition that will fail this test, as I mentioned up there. In other words, the guilty course CCAddUiTest.course1 persists after the test.
1. Under the old code
The code straightaway goes to `testContent()`. No problem in the first comparison, `coursesPage.verifyHtml("/instructorCoursesNoCourse.html")`. The second comparison, `coursesPage.verifyHtmlMainContent("/instructorCoursesMultipleCourses.html")`, because of the presence of that guilty course, will fail. And once happened, this will be _permanent_ because no part of the code up to there deletes the course.
2. Under the re-written code
Before going to test content, the guilty course (if present) will be deleted through the BackDoor operation. Thus it's the same as starting the test freshly.
The presence of that `BackDoor.deleteCourse` tells that the whoever wrote this test file before already anticipated that failure, which is good. Only that it's not placed correctly.

Comment (wkurniawan07) [inline src/test/java/teammates/test/cases/ui/browsertests/InstructorCoursesPageUiTest.java]: If you're interested to try, just fail the test anytime _after line 217, before line 269_ is executed. I can guarantee that the subsequent runs will be a 100% failure at line 128.
