### PR TITLE
studentFeedbackSubmissionEditSave: java.lang.AssertionError: null #4398

### LINKED ISSUE #4398: studentFeedbackSubmissionEditSave: java.lang.AssertionError: null
Request Method POST
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36
Request Url https://teammatesv4.appspot.com/page/studentFeedbackSubmissionEditSave
Request Path /page
Request Parameters {omitted for privacy}
Stack Trace

java.lang.AssertionError: null
	at teammates.common.util.Assumption.fail(Assumption.java:59)
	at teammates.common.util.Assumption.fail(Assumption.java:66)
	at teammates.logic.core.FeedbackResponsesLogic.createFeedbackResponse(FeedbackResponsesLogic.java:53)
	at teammates.logic.api.Logic.createFeedbackResponse(Logic.java:2187)
	at teammates.ui.controller.FeedbackSubmissionEditSaveAction.saveResponse(FeedbackSubmissionEditSaveAction.java:213)
	at teammates.ui.controller.FeedbackSubmissionEditSaveAction.execute(FeedbackSubmissionEditSaveAction.java:137)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:37)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:260)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:78)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:147)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:457)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:235)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by kanghj**
Fixes #4398

### CODE REVIEW

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java [hunk 1]
```diff
@@ -421,6 +421,75 @@ public void updateFeedbackResponse(
...
+        if (oldResponseEntity == null) {
+            throw new NullPointerException("oldResponseEntity should not be null");
+        }
+        
+        // Create a copy.
+        FeedbackResponseAttributes newResponse = new FeedbackResponseAttributes(updatedResponse);
+        
+        FeedbackResponseAttributes oldResponse = new FeedbackResponseAttributes(oldResponseEntity);
+
+        copyOldResponseToNewResponse(newResponse, oldResponse);
```
Comment (damithc) [inline src/main/java/teammates/logic/core/FeedbackResponsesLogic.java]: This `copyOldResponseToNewResponse` method can be error prone because it does not return anything but causes a side effect. It's not immediately clear which object is copied to which. Can we move it to `FeedbackResponseAttributes`? Or may be make it a constructor of `FeedbackResponseAttributes`?

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java [hunk 2]
```diff
@@ -421,6 +421,75 @@ public void updateFeedbackResponse(
...
+     *                                       a response with the same id already exist. 
+     * @throws InvalidParametersException               
+     */
+    public void updateFeedbackResponse(
+                        FeedbackResponseAttributes updatedResponse,
+                        FeedbackResponse oldResponseEntity)
+                                throws InvalidParametersException, EntityAlreadyExistsException {
+        if (oldResponseEntity == null) {
+            throw new NullPointerException("oldResponseEntity should not be null");
+        }
```
Comment (damithc) [inline src/main/java/teammates/logic/core/FeedbackResponsesLogic.java]: Shouldn't this be an assertion?

File: src/main/java/teammates/logic/core/FeedbackResponsesLogic.java (hunk 1 above)
Comment (kanghj) [inline src/main/java/teammates/logic/core/FeedbackResponsesLogic.java]: Rewriting this so that that method isn't needed anymore.
