### PR TITLE
Wrong logic for getArchivedCourseIds in CoursesLogic #4288

### LINKED ISSUE #4288: Wrong logic for getArchivedCourseIds in CoursesLogic

### PR DESCRIPTION
**Pull request by LowWeiLin**
Fixes #4288

### CODE REVIEW

File: src/main/java/teammates/logic/core/CoursesLogic.java [hunk 1]
```diff
@@ -795,14 +795,18 @@ public boolean isCourseArchived(CourseAttributes course, InstructorAttributes in
...
-        }
         for (InstructorAttributes instructor : instructorList) {
             if (instructor.isArchived != null && instructor.isArchived == true) {
                 archivedCourseIds.add(instructor.courseId);
+            } else if (instructor.isArchived == null) {
+                for (CourseDetailsBundle cdb : allCourses) {
+                    if (cdb.course.id == instructor.courseId) {
+                        if (cdb.course.isArchived) {
+                            archivedCourseIds.add(cdb.course.id);
+                        }
```
Comment (kanghj) [inline src/main/java/teammates/logic/core/CoursesLogic.java]: This is hard to read. We have a <code>isCourseArchived</code> in Logic, we can move that method into CoursesLogic, and use that here?

Comment (LowWeiLin) [inline src/main/java/teammates/logic/core/CoursesLogic.java]: Refactored the code
