### PR TITLE
 NPE in InstructorCourseStudentDetailsEditSaveAction #4218

### LINKED ISSUE #4218: NPE in InstructorCourseStudentDetailsEditSaveAction
java.lang.NullPointerException
	

Request Path /page 
Request Parameters {studentemail::....@kennesaw.edu, submit::Save Changes, teamname::5, newstudentemail::...@gmail.com, user::......, studentname::Noel Smith, courseid::2MGT4001W2-Fall2015, comments::} 
Stack Trace

java.lang.NullPointerException
	at teammates.ui.controller.InstructorCourseStudentDetailsEditSaveAction.execute(InstructorCourseStudentDetailsEditSaveAction.java:36)
	at teammates.ui.controller.Action.executeAndPostProcess(Action.java:337)
	at teammates.ui.controller.ControllerServlet.doPost(ControllerServlet.java:59)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:637)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at teammates.storage.datastore.DatastoreFilter.doFilter(DatastoreFilter.java:28)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.appstats.AppstatsFilter.doFilter(AppstatsFilter.java:142)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.ParseBlobUploadFilter.doFilter(ParseBlobUploadFilter.java:125)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.runtime.jetty.SaveSessionFilter.doFilter(SaveSessionFilter.java:35)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.JdbcMySqlConnectionCleanupFilter.doFilter(JdbcMySqlConnectionCleanupFilter.java:60)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.apphosting.utils.servlet.TransactionCleanupFilter.doFilter(TransactionCleanupFilter.java:43)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.apphosting.runtime.jetty.AppVersionHandlerMap.handle(AppVersionHandlerMap.java:257)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at com.google.apphosting.runtime.jetty.RpcRequestParser.parseAvailable(RpcRequestParser.java:76)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at com.google.apphosting.runtime.jetty.JettyServletEngineAdapter.serviceRequest(JettyServletEngineAdapter.java:146)
	at com.google.apphosting.runtime.JavaRuntime$RequestRunnable.run(JavaRuntime.java:468)
	at com.google.tracing.TraceContext$TraceContextRunnable.runInContext(TraceContext.java:437)
	at com.google.tracing.TraceContext$TraceContextRunnable$1.run(TraceContext.java:444)
	at com.google.tracing.CurrentContext.runInContext(CurrentContext.java:230)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref(TraceContext.java:308)
	at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext(TraceContext.java:300)
	at com.google.tracing.TraceContext$TraceContextRunnable.run(TraceContext.java:441)
	at com.google.apphosting.runtime.ThreadGroupPool$PoolEntry.run(ThreadGroupPool.java:234)
	at java.lang.Thread.run(Thread.java:745)

### PR DESCRIPTION
**Pull request by yj-soh**
Fixes #4218 

A similar problem happens clicking on the "Edit" link pointed at an invalid student.
(e.g. open edit link in new tab, edit student's email, click on edit link in initial tab)

Also, the other buttons reply only with error messages like "The student you tried to view details for does not exist." aside from Delete which returns a success. Should any of their behaviour be changed to be consistent with this one or vice versa (regarding the line about eventual consistency)?

Should either of those be handled in this PR?

(Regarding the delete button, it's due to a method that "Fails silently if no match found." according to its comment.)

### CODE REVIEW

**Comment by damithc** [comment]
Yes, changing the rest to be consistent is good, but can be done separately.

File: src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java [hunk 1]
```diff
@@ -33,6 +33,11 @@ public ActionResult execute() throws EntityDoesNotExistException {
         boolean hasSection = logic.hasIndicatedSections(courseId);
         StudentAttributes student = logic.getStudentForEmail(courseId, studentEmail);
         
+        boolean studentNotFound = student == null;
+        if (studentNotFound) {
```
Comment (wkurniawan07) [inline src/main/java/teammates/ui/controller/InstructorCourseStudentDetailsEditSaveAction.java]: If the variable is not used anywhere else you can just `if (student == null)`.

**Comment by wkurniawan07** [comment]
Minor change requested (and it's not that important), after addressing that if you so wishes, go ahead and merge.

File: src/main/java/teammates/common/util/Const.java [hunk 2]
```diff
@@ -875,6 +875,7 @@
         public static final String STUDENT_GOOGLEID_RESET_FAIL = "An error occurred when trying to reset student's google id";
         
         public static final String STUDENT_EDITED = "The student has been edited successfully";
+        public static final String STUDENT_NOT_FOUND = "The student you tried to edit does not exist. If the student was created during the last few minutes, try again in a few more minutes as the student may be being saved.";
```
Comment (damithc) [inline src/main/java/teammates/common/util/Const.java]: The line is too long.
`... as the student data may still be being saved.`?

**Comment by damithc** [comment]
Can we cover this in a test? Or is it already being covered?

**Comment by yj-soh** [comment]
Sorry, @wkurniawan07, I added a test for it, so take another look at this, please.
That other PR's dev green, so I'll merge them both in after you give the okay.

File: src/main/java/teammates/common/util/Const.java (hunk 2 above)
Comment (damithc) [inline src/main/java/teammates/common/util/Const.java]: This comment not addressed.

Comment (yj-soh) [inline src/main/java/teammates/common/util/Const.java]: It was done in the related PR where the second sentence was extracted to be appended onto the other error messages.
I believe there shouldn't be a need to duplicate the change here when that PR is planned to be merged into this one.

**Comment by wkurniawan07** [comment]
Looks good to merge :+1:
